version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9002:9000"   # MinIO API
      - "9003:9001"   # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  milvus:
    image: milvusdb/milvus:latest
    container_name: milvus-standalone
    depends_on:
      - minio
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_USE_SSL: "false"
      MINIO_BUCKET_NAME: milvus-bucket
      ETCD_USE_EMBED: "true"
    command: ["milvus", "run", "standalone"]
    volumes:
      - milvus_data:/var/lib/milvus

volumes:
  minio_data:
  milvus_data:
